// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkqqhuvhcndqmypdkrgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcXFodXZoY25kcW15cGRrcmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODU2OTksImV4cCI6MjA3NDE2MTY5OX0.WEX2zvOQrgqB5dwNfmkSy7Lj-EHhxt_5DIzkA-ovv1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});